# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='adress',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
