# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_cart', '0002_auto_20171221_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='adress',
            new_name='address',
        ),
    ]
